Update patch set 1
Patch Set 1:

> Patch Set 1: Verified-1
> 
> I am getting a build error after selecting the all of the topic android-11.0.0_r32.
> The error appears to be caused by 304894 but after removing this there appear to be others which may be caused by interdependencies. It will take time to dig deeper, there are 53 changes in this topic.
> 
> FAILED: out/soong/build.ninja
> out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b out/soong -n out -d out/soong/build.ninja.d -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/build.ninja Android.bp
> error: prebuilts/clang/host/linux-x86/Android.bp:34:1: module "libclang_rt.builtins-arm-android" variant "android_arm_armv7-a-neon_static": module source path "prebuilts/clang/host/linux-x86/clang-r383902b1/lib64/clang/11.0.2/lib/linux/libclang_rt.builtins-arm-android.a" does not exist
> error: prebuilts/clang/host/linux-x86/Android.bp:683:1: module "libclang_rt.fuzzer-arm-android" variant "android_arm_armv7-a-neon_static": module source path "prebuilts/clang/host/linux-x86/clang-r383902b1/lib64/clang/11.0.2/lib/linux/libclang_rt.fuzzer-arm-android.a" does not exist
> error: prebuilts/clang/host/linux-x86/Android.bp:623:1: module "libclang_rt.fuzzer-x86_64" variant "linux_glibc_x86_64_static": module source path "prebuilts/clang/host/linux-x86/clang-r383902b1/lib64/clang/11.0.2/lib/linux/libclang_rt.fuzzer-x86_64.a" does not exist
> 15:24:51 soong bootstrap failed with: exit status 1

Cannot reproduce. Did you actually either manually re-init your repo against the manifest change or apply the manifest change to .repo/manifests (I traditionally to the latter)?

clang-r383902b1 isn't in r29. It is in r32. This indicates that you don't have r32 synced in prebuilts/clang/host/linux-x86.

Patch-set: 1