Update patch set 4
Patch Set 4:

> root@build:~/ishant/kyleproxx/cm14# repopick -t OMS7
 > Traceback (most recent call last):
 > File "/root/ishant/kyleproxx/cm14/vendor/cm/build/tools/repopick.py",
 > line 289, in <module>
 > mergables[-1]['fetch'] = review['revisions'][review['current_revision']]['fetch']
 > KeyError: 'current_revision'
 > Any help? How to pick all commits at once?

Best way is to cherry-pick all the commits that are in the OMSrootless branch on my Github. If you repopick like this, you can have merge conflicts since it won't be in the correct order.

Patch-set: 4