Update cm.xml
due to this:
error: Cannot fetch LineageOS/android_external_fsck_msdos (IOError: [Errno 14] Bad address)
error: Cannot fetch LineageOS/android_packages_apps_Trebuchet (IOError: [Errno 14] Bad address)
Fetching project LineageOS/android_external_tinyxml2
error: Cannot fetch LineageOS/android_external_tinyxml2 (GitError: config: [Errno 14] Bad address)

i have found that these addresses were missing