Update patch set 38
Patch Set 38:

I was just updating the patch since https://review.cyanogenmod.org/#/c/158468/ was merged.

The following are still issues and need to be forked or switched to AOSP
error: Cannot fetch CyanogenMod/android_packages_apps_EmergencyInfo
error: Cannot fetch CyanogenMod/android_packages_apps_TV
error: Cannot fetch CyanogenMod/android_packages_providers_BlockedNumberProvider

Patch-set: 38