Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> I failed with this "repopick -t P_asb_2019-09". Wrote:Applying change number 255693...
> ERROR: For 255693, could not determine the project path for project LineageOS/android_system_nfc
> 
> Manual (one by one) worked for me except this 255693, 255694, 255696, 255697 (ERROR: For 2556XX, could not determine the project path for project ...) {repo sync a while ago}

You need to sync with the patched manifest git. i.e.: https://github.com/nvertigo/android/tree/nlos-16.0

Patch-set: 1
Reviewer: Gerrit User 12847 <12847@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>