manifest: change .. to github.com
Change remote to use github.com instead of ..

This is to resolve the following error when trying to sync from France.
error: cannot expand target domain name in SRV RR
fatal: Unable to look up github.com

Change-Id: Id2c98742437b8ab8cbefc41d73b512ed53ef5e29